# Generated by Django 6.0.4 on 2026-05-02 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_breed_alter_animal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name'], 'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/', verbose_name="Photo de l'animal"),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Stérilisé'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_vaccinated',
            field=models.BooleanField(default=False, verbose_name='Vacciné'),
        ),
        migrations.AddField(
            model_name='animal',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='Notes médicales'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(help_text='Âge en mois', verbose_name='Âge (mois)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.breed', verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'animal"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('other', 'Other')], max_length=50, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('available', 'Available for Adoption'), ('adopted', 'Already Adopted'), ('medical', 'Medical Care'), ('reserved', 'Reserved for Adoption')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la race'),
        ),
    ]
