# Generated by Django 6.0.4 on 2026-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_breed_options_animal_color_animal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Race'),
        ),
    ]
