# Generated by Django 6.0.4 on 2026-05-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_breed_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopters', to='animals.animal', verbose_name='Animal souhaité')),
            ],
            options={
                'verbose_name': 'Adoptant',
                'verbose_name_plural': 'Adoptants',
                'ordering': ['-created_at'],
            },
        ),
    ]
