# Generated by Django 6.0.4 on 2026-06-15 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_adopter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Médicament / Produit')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix (€)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('for_species', models.CharField(blank=True, max_length=100, verbose_name='Espèces concernées')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Pharmacie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du vétérinaire')),
                ('specialty', models.CharField(blank=True, max_length=120, verbose_name='Spécialité')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
            ],
            options={
                'verbose_name': 'Vétérinaire',
                'verbose_name_plural': 'Vétérinaires',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hauteur (cm)'),
        ),
        migrations.CreateModel(
            name='AnimalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date de mesure')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hauteur (cm)')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, verbose_name='Observations vétérinaires')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Fiche de santé',
                'verbose_name_plural': 'Fiches de santé',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=120, verbose_name='Dosage')),
                ('start_date', models.DateField(verbose_name='Début du traitement')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin du traitement')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='animals.animal', verbose_name='Animal')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='animals.medication', verbose_name='Médicament')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='animals.vet', verbose_name='Vétérinaire')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Date du rendez-vous')),
                ('reason', models.CharField(max_length=200, verbose_name='Raison du rendez-vous')),
                ('outcome', models.TextField(blank=True, verbose_name='Résultat / recommandations')),
                ('follow_up', models.BooleanField(default=False, verbose_name='Suivi requis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animals.animal', verbose_name='Animal')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='animals.vet', verbose_name='Vétérinaire')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
